Geometry
========
The [geometry](api/ktk.geometry.rst) module simplifies the calculation of linear algebric operations on
series of points, vectors and transformation matrices.

Array convention
----------------------

Every point, vector or matrix is considered as a series, where the dimensions
of the array are:

- First dimension (N) : time. Constants are also reprented as series: they have only one data on the first dimension.

- Second dimension (4) : point/vector coordinates, or matrix line.

- Third dimension (M, optional) : point index (for sets of point), or matrix column.

For example, floats, points, vectors, sets and matrices are expressed as following:

**Single float**

    [a]
    
    value = array[0]

**Series of floats**

    [a(t0), a(t1), a(t2), ...]
    
    value = array[i_time]

**Series of points**

    [[x(t0), y(t0), z(t0),  1.],
     [y(t1), y(t1), z(t1),  1.],
     [y(t2), y(t2), z(t2),  1.],
     [ ... ,  ... ,  ... , ...]]
     
    value = array[i_time, i_coordinate]

**Series of vectors**

    [[x(t0), y(t0), z(t0),  0.],
     [y(t1), y(t1), z(t1),  0.],
     [y(t2), y(t2), z(t2),  0.],
     [ ... ,  ... ,  ... , ...]]
     
    value = array[i_time, i_coordinate]


**Series of sets of point**

    [[[x1(t1), x2(t1), x3(t1), x4(t1)],
      [y1(t1), y2(t1), y3(t1), y4(t1)],
      [z1(t1), z2(t1), z3(t1), z4(t1)],
      [  1.,     1.,     1.,      1. ]],

     [[x1(t2), x2(t2), x3(t2), x4(t2)],
      [y1(t2), y2(t2), y3(t2), y4(t2)],
      [z1(t2), z2(t2), z3(t2), z4(t2)],
      [  1.,     1.,     1.,     1.  ]],
      
      ...
     ]
     
    value = array[i_time, i_coordinate, i_point]

**Series of matrices**

    [[[R11(t1), R12(t1), R13(t1), Tx(t1)],
      [R21(t1), R22(t1), R23(t1), Ty(t1)],
      [R31(t1), R32(t1), R33(t1), Tz(t1)],
      [   0.,      0.,      0.,     1.  ]],

     [[R11(t2), R12(t2), R13(t2), Tx(t2)],
      [R21(t2), R22(t2), R23(t2), Ty(t2)],
      [R31(t2), R32(t2), R33(t2), Tz(t2)],
      [   0.,      0.,      0.,     1.  ]],

      ...
     ]
     
    value = array[i_time, i_row, i_column]

In [1]:
import ktk
import numpy as np

Matrix multiplication
-------------------------

To facilitate the multiplication of series, ktk.geometry provides a `matmul` function that matches both matrices' time dimensions before applying the numpy's @ or * operator accordingly on each time iteration. Therefore, when dealing with series of floats, vectors, points or matrices, it is advisable to use ktk.geometry's `matmul` instead of the @ operator, which will garranty to follow ktk's array convention. For example:

**Matrix multiplication between a matrix and a series of points**

In [2]:
# Single rigid transformation matrix
T = np.array([[[1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]]])

# Series of 3 points
points = np.array([[0, 1, 0, 1],
                   [1, 1, 0, 1],
                   [2, 1, 0, 1]])

ktk.geometry.matmul(T, points)

array([[0., 1., 0., 1.],
       [1., 1., 0., 1.],
       [2., 1., 0., 1.]])

**Multiplication between a series of floats and a series of vectors**

In [3]:
# Series of 3 floats
floats = np.array([0., 0.5, 1., 1.5])

# Series of 3 vectors
vectors = np.array([[1, 1, 0, 0],
                    [2, 1, 0, 0],
                    [3, 1, 0, 0],
                    [4, 1, 0, 0]])

ktk.geometry.matmul(floats, vectors)

array([[0. , 0. , 0. , 0. ],
       [1. , 0.5, 0. , 0. ],
       [3. , 1. , 0. , 0. ],
       [6. , 1.5, 0. , 0. ]])

**Dot product between a series of points and a single point**

In [4]:
# Series of 3 points
points = np.array([[0, 1, 0, 1],
                   [1, 1, 0, 1],
                   [2, 1, 0, 1]])

# Single point
point = np.array([[2, 3, 4, 1]])

ktk.geometry.matmul(points, point)

array([4., 6., 8.])

Creating series of rotation matrices
------------------------------------
The function `ktk.geometry.create_rotation_matrices` allows creating series of Nx4x4 matrices around a given axis. For example, this command creates a rotation matrix of 90 degrees around the x axis. Note that the angle argument is a list or an array, to comply with the `ktk.geometry`'s convention above.

In [5]:
ktk.geometry.create_rotation_matrices('x', [np.pi/2])

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.]]])

As another example, this will create a series of 100 rotation matrices around the z axis, from 0 to
360 degrees:

In [6]:
ktk.geometry.create_rotation_matrices('z', np.linspace(0, 2 * np.pi, 100))

array([[[ 1.        , -0.        ,  0.        ,  0.        ],
        [ 0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]],

       [[ 0.99798668, -0.06342392,  0.        ,  0.        ],
        [ 0.06342392,  0.99798668,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]],

       [[ 0.99195481, -0.12659245,  0.        ,  0.        ],
        [ 0.12659245,  0.99195481,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]],

       ...,

       [[ 0.99195481,  0.12659245,  0.        ,  0.        ],
        [-0.12659245,  0.99195481,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.

Creating series of reference frames
-----------------------
Let's say we have the position of three markers, and we want to create a reference frame based on these markers. This is the aim of the `create_reference_frames` function.

If the markers are at these positions (0, 0, 0), (1, 0, 0) and (0, 1, 0):

In [7]:
global_markers = np.array(
    [[[0., 1., 0.],
      [0., 0., 1.],
      [0., 0., 0.],
      [1., 1., 1.]]])

Now we can create a reference frame based on these three markers. Please consult the [API reference](api/ktk.geometry.rst) for the different marker configurations available for the creation of reference frames.

In [8]:
T = ktk.geometry.create_reference_frames(global_markers)

T

array([[[-0.70710678,  0.70710678,  0.        ,  0.33333333],
        [-0.70710678, -0.70710678,  0.        ,  0.33333333],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]])

Calculating local coordinates
---------------------
We now have a reference frame defined from three markers. If we are interested to know the local position of these markers in the new-created frame, we can use the function `get_local_coordinates`.

In [9]:
local_markers = ktk.geometry.get_local_coordinates(global_markers, T)

local_markers

array([[[ 0.47140452, -0.23570226, -0.23570226],
        [ 0.        ,  0.70710678, -0.70710678],
        [ 0.        ,  0.        ,  0.        ],
        [ 1.        ,  1.        ,  1.        ]]])

Calculating global coordinates
----------------------
In the case we have the markers' local coordinates and we would like to express these markers in the global reference frame, we would use the mirror function `get_global_coordinates`.

In [10]:
ktk.geometry.get_global_coordinates(local_markers, T)

array([[[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [1., 1., 1.]]])

in which case the results is effectively the global points as we defined them at the beginning.

For more information on geometry, please check the [API Reference](api/ktk.geometry.rst).