Dimension conventions and first example
=======================================

In the [geometry](../api/kineticstoolkit.geometry.rst) module and in most of Kinetics Toolkit's module:

- Every point, vector or matrix, and in many case even scalar, is considered as a **series**.
- The first dimension of any series corresponds to **time**.

To understand better how to express scalars, coordinates (points, vectors, frames) and homogeneous transforms as series, please refer to the following pictures:

Series of scalars
-----------------

![Series of m scalars](../_static/geometry/series_of_m_scalars.png){ width=330px }

Series of points, series of vectors
-----------------------------------

![Series of m points](../_static/geometry/series_of_m_points.png){ width=330px } ![Series of m vectors](../_static/geometry/series_of_m_vectors.png){ width=330px }

Series of groups of points, series of groups of vectors
-------------------------------------------------------

![Series of m groups of n points](../_static/geometry/series_of_m_groups_of_n_points.png){ width=330px } ![Series of m groups of n vectors](../_static/geometry/series_of_m_groups_of_n_vectors.png){ width=330px }

Series of frames/homogeneous transforms
---------------------------------------

![Series of m transformation matrices](../_static/geometry/series_of_m_transformation_matrices.png){ width=350px }

Working with constants
----------------------

Since most signals in Kinetics Toolkit as considered as a series, always ensure that the first dimension of any array is reserved to time. For example, the vector (x = 1, y = 2, z = 3) must be expressed as `np.array([[1.0, 2.0, 3.0, 0.0]])` (note the double brackets). A common error would be to express it as `np.array([1.0, 2.0, 3.0, 0.0])` (single brackets), which would mean a series of 4 floats instead of one constant vector.

A quick way to convert a constant array to a series is to use numpy's `newaxis`:

In [1]:
import numpy as np

one_matrix = np.eye(4)
one_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [2]:
series_of_one_matrix = one_matrix[np.newaxis]
series_of_one_matrix

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]])

First example with the geometry module
--------------------------------------

Now that we presented the conventions for expressing coordinates and transforms as series, we are ready to redo the last example from the last section, this time using Kinetics Toolkit.

----------------------

![humerus_frame](../_static/geometry/humerus_frame.png){height=250px}

Figure 1. Position and orientation of the humerus.

----------------------

We know the lenght of the arm is 38 cm, and we want to express the position of the elbow in the global coordinate system. The shoulder is located 15 cm forward and 70 cm upward to the global origin and the humerus is inclined at 30 degrees of the vertical.

First, let's express the elbow position in the humerus coordinate system.

In [3]:
import kineticstoolkit.lab as ktk

local_elbow_position = np.array([[0, -0.38, 0, 1]])

local_elbow_position

array([[ 0.  , -0.38,  0.  ,  1.  ]])

Now, we create the frame representing the position and orientation of the humerus coordinate system. Since we know these position and orientation, then we will create this frame as an homogeneous transform from the global to the humerus coordinate system, using the [create_transforms()](../api/kineticstoolkit.geometry.rst#kineticstoolkit.geometry.create_transforms) function:

In [4]:
humerus_frame = ktk.geometry.create_transforms(
    seq = 'z',
    angles = [np.deg2rad(30)],
    translations = [[0.15, 0.70, 0]])

humerus_frame

array([[[ 0.8660254, -0.5      ,  0.       ,  0.15     ],
        [ 0.5      ,  0.8660254,  0.       ,  0.7      ],
        [ 0.       ,  0.       ,  1.       ,  0.       ],
        [ 0.       ,  0.       ,  0.       ,  1.       ]]])

Now we can express the local elbow position in the global coordinate system:

In [5]:
ktk.geometry.get_global_coordinates(local_elbow_position, humerus_frame)

array([[0.34      , 0.37091035, 0.        , 1.        ]])